### ISSUE TITLE
Did something change? Not working at all anymore for me.

### ISSUE THREAD

**Issue by vesper8** [permafrost-dev/vue-ray#123]
I hadn't used vue-ray in a while and today I'm trying to use it again and no matter what I do I cannot get anything to be sent to Ray.

Even with the most basic setup. Is it still working for you?

**Comment by patinthehat** [comment]
Sorry for the late response @vesper8 - all tests are passing and it appears to be working.  Could you provide an example repo/code sample of your setup and what isn't working for you?

**Comment by patinthehat** [comment]
Closed due to inactivity. Please open a new issue if you're still experiencing an issue. Thanks!
