### ISSUE TITLE
not working with nuxt 2

### ISSUE THREAD

**Issue by Ok9xNirab** [permafrost-dev/vue-ray#157]
**not working with nuxt 2**

![Screenshot 2023-09-10 at 2 33 38 PM](https://github.com/permafrost-dev/vue-ray/assets/40653908/460f55ff-e099-48c4-91f6-508b25834244)

**nuxt.config.js**
```js
export default {
  build: {
    extend(config) {
      config.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      })
    },
  },
}
```

**ray.js** [Plugin]

```js
const Vue = require("vue");
const { RayPlugin } = require("vue-ray/vue2");

Vue.use(RayPlugin, {
  interceptErrors: true,
  host: "127.0.0.1",
  showComponentEvents: ["mounted"],
  nodeRaySettings: {
    interceptConsoleLog: false,
  },
});

```

**Comment by patinthehat** [comment]
@Ok9xNirab can you provide a sample project demonstrating that it's not working as expected? Thanks! :+1:

**Comment by patinthehat** [comment]
Closed due to inactivity.  If you're still experiencing a problem, please open a new issue. Thanks! :+1:
