### ISSUE TITLE
How can I call $ray in vue setup api

### ISSUE THREAD

**Issue by Ok9xNirab** [permafrost-dev/vue-ray#158]
Any guide about `vue-ray with Nuxt 3`

I've setup this via plugin & works fine within option API.
But I can't find a way use this within vue3 setup api.

**ray.client.ts**
```ts
import RayPlugin from "vue-ray";

export default defineNuxtPlugin(({ vueApp }) => {
  vueApp.use(RayPlugin, {
    interceptErrors: true,
    host: "127.0.0.1",
    port: 23517,
  });
});

```

**Thanks**

**Comment by patinthehat** [comment]
@Ok9xNirab You may have to use [node-ray](https://github.com/permafrost-dev/node-ray) instead of this plugin as new features are on hold for this package right now. If you can, please provide a sample project that demonstrates the issue you're experiencing.

**Comment by patinthehat** [comment]
Closed due to inactivity.  If you're still experiencing a problem, please open a new issue. Thanks! :+1:
