### ISSUE TITLE
Does not check if Ray is running and no console errors are shown anymore, everything is directed to Ray (even when unavailable)

### ISSUE THREAD

**Issue by ThaDaVos** [permafrost-dev/vue-ray#27]
**Describe the bug**
Like the title says, after installing and setting up this plugin it always tries to sent to Ray, even is previous requests have failed as Ray is not enabled, maybe the state of ray should be cached until a page refresh?

Also, after installing this, enabling `interceptErrors` - no errors are shown in the browser console anymore, I rather have this as an extra option as sometimes it's easier to debug these errors in the browser (as I am using sourcemaps and am able to click to their location, which seems also to be missing)

**To Reproduce**

1. Install `vue-ray`
2. enable `interceptErrors`
3. Create an error somewhere

**Expected behavior**

See the error in the console and, only if Ray is open, see the error in Ray too

**Screenshots**

None

**Environment (please complete the following information):**

 - OS: Windows 10
 - Vue Version [e.g. 2.6, 3.0]: 2.6.x
 - Language & Version [e.g. Babel, Typescript 4.1]: Webpack based, so probably Babel as it's Laravel Mix

**Additional context**

**Comment by patinthehat** [comment]
Thanks for this! I'll look into changing the behavior.

**Comment by ThaDaVos** [comment]
Great! Also a question, why do you use a mixin to inject `$ray` instead of setting it on the prototype?
I am asking this as I would love to add ray also to my axios interceptors to intercept requests and responses but I cannot access ray through `Vue.prototype.$ray` or any other way as it's injected into components only

**Comment by patinthehat** [comment]
@ThaDaVos If I recall correctly, it had to do with an issue I encountered because the package supports both vue 2 and 3. 

As a workaround, you can import the [`node-ray`](https://github.com/permafrost-dev/node-ray) package (which is used by this package), which provides direct access to a ray instance.  Let me know if you run into any issues.

**Comment by patinthehat** [comment]
Closed due to inactivity. Please open a new issue if you're still experiencing an issue. Thanks!
