### ISSUE TITLE
Webpack build dep (?) error in big Laravel + VueJs 2 project

### ISSUE THREAD

**Issue by Gompje** [permafrost-dev/vue-ray#5]
disclaimer: I'm not sure if this package is even supposed to work outside a NodeJs project. it sure would be FANTASTIC to be able to use ray on both the back and frontend. especially for my huge monolith app.

**Describe the bug**

```
WARNING in ./node_modules/minimatch/minimatch.js 6:9-24
Module not found: Error: Can't resolve 'path' in '<snip>/node_modules/minimatch'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }
```

**To Reproduce**

- Existing project with L8, VueJs 2 whole lot of packages + Webpack 5.x and Laravel mix to build the dep
- Lots of configs in the webpack build
- Builds fine
- Follow the guide to install this package → VueJs 2; including the Vuex
- Build fails with error above

**Expected behavior**

Builds. 
(and Being able to use Ray instead of console.log)

**Environment (please complete the following information):**
- Catalina; yarn
 - Vue version: '2.6.12',
 - Plain js
 - webpack version: '5.24.4',
 - laravel mix version: '6.0.13',

**Comment by patinthehat** [comment]
@Gompje It sure does work outside of a nodejs project: it works in javascript, typescript, etc.  
Anyway, I think I know what the issue is - I'm looking into it now.  Shouldn't take long...  stand by. :hourglass:

**Comment by patinthehat** [comment]
In the mean time, you can add the following to your webpack config to get it to compile without that error:

```js
resolve: {
    fallback: { "path": false },
}
```

**Comment by patinthehat** [comment]
@Gompje Please update `vue-ray` to `v1.13.2` or higher.  Does this fix the issue?

**Comment by Gompje** [comment]
@patinthehat → testing now, missed the notification; guess it's time for bed (in the EU)

**Comment by Gompje** [comment]
@patinthehat it does mix now; but doesn't run

console error:
```
vendor.js:288350 Uncaught ReferenceError: require is not defined
    at Module../node_modules/vue-ray/dist/vue2.mjs (vendor.js:288350)
    at __webpack_require__ (manifest.js:22)
    at Module../resources/js/app.js (app.js:26981)
    at __webpack_require__ (manifest.js:22)
    at checkDeferredModulesImpl (manifest.js:324)
    at webpackJsonpCallback (manifest.js:306)
    at app.js:1
```
I used the import, but I do use require as well for others. And tested, to be sure with both = no dice. 

I'm going  to bed now. I can test again tomorrow, faster given I now _did_ stash my changes...

**Comment by patinthehat** [comment]
@Gompje version `1.13.3` removes the `require()` call altogether and replaces it with an import.  Please let me know if the problem persists.

**Comment by Gompje** [comment]
Positive news: it runs!
negative: we have an unending loop.. I tried to capture the output with a screenshot. 
I had no other $ray calls in code, except those on the store. I do use vuex a lot (lot of mutations)

Guess Ray really could benefit from a pauze button or output file option 😏 

<img width="1144" alt="Screenshot 2021-03-12 at 14 06 08" src="https://user-images.githubusercontent.com/1011327/110944169-5eff5400-833c-11eb-8eb1-d133e3410863.png">

**Comment by patinthehat** [comment]
Can you provide a sample repo or webpack config so I can reproduce this error?

**Comment by patinthehat** [comment]
@Gompje As an alternative, if you need this working now and don't want to wait for a fix, you can always do this in your entry point `main.js` _(or whatever)_:

_npm install node-ray_

```js
import { ray } from 'node-ray/web';
window.ray = ray;
```

You can then access `ray()` in your methods.  For example:
```js
// ...
methods: {
    sendTest() {
        ray('test').blue().large();
    },
},
// ...
```
You just won't have access to the features of `vue-ray` until I've tracked down and fixed this issue.

**Comment by Gompje** [comment]
In a meeting right now, will look after that :)

**Comment by Gompje** [comment]
> @Gompje As an alternative, if you need this working now and don't want to wait for a fix, you can always do this in your entry point `main.js` _(or whatever)_:
> 
> _npm install node-ray_
> 
> ```js
> import { ray } from 'node-ray/web';
> window.ray = ray;
> ```
> 
> You can then access `ray()` in your methods. For example:
> 
> ```js
> // ...
> methods: {
>     sendTest() {
>         ray('test').blue().large();
>     },
> },
> // ...
> ```
> 
> You just won't have access to the features of `vue-ray` until I've tracked down and fixed this issue.

It's not that urgent btw - the bug is already fixed the old fashion (hard) way 😏 
anyway
let tackle this loop

I had this in app.js: (your example code)
```
Vue.use(RayPlugin, {
  interceptErrors: true,
  host: '127.0.0.1',
  showComponentEvents: ['mounted'],
})
```
and this app does have many many components, may api calls as well
but even when I removed the test ` this.$ray().data()` call inside one components `created` the loop persisted

in vuex I have your example code as well: (its a huge one file store thing, I still need to refactor that one)
```
  plugins: [
    RayVuexPlugin({
      trackState: true,
      logMutations: true,
      trackingOptions: {
        propNames: ['on*'],
      },
    }),
  ],
```

I'm now testing without this plugin config and see what it does, hoping to trigger the error ones or see what line that is on. This is a huge project - could be any of the -tig packages causing this

**Comment by Gompje** [comment]
no dice, but at least it now stops after -tig times, meaning its imho not really unending just high level and a lot is going on in my app

**Comment by Gompje** [comment]
🙄  and off course → its because I log the 'mounted' event with the settings of this package which fails on that $ray not found thing.

**Comment by patinthehat** [comment]
That tells me what/where the actual issue is - stand by.

**Comment by Gompje** [comment]
@patinthehat → Think we are on something →  it works without that auto-log hook and the window, plain js method

**Comment by patinthehat** [comment]
@Gompje I was able to reproduce the  "Cannot read property..." error, and it should be fixed in version `1.13.4+` _(just published)_.  Everything works for me now in terms of intercepting events in Vue 2.

**Comment by Gompje** [comment]
Yes! it works now, and I do have a lot of components (using vuetify as well)
<img width="848" alt="Screenshot 2021-03-12 at 15 25 51" src="https://user-images.githubusercontent.com/1011327/110953161-56f8e180-8347-11eb-907c-b12d23acfb4e.png">

first 2 are vuetify ones, and the last one 1 of mine. Minor issue with the unknown.js
maybe an option to exclude vendor components? 

Anyway I'm very happy I can use Ray now to debug JS. Wonder if this will be a lifechanger like it has been for php. Finally no more console.log after 20 years 🎉  

Thanks for your (very) quick response; count on me to help test and report odd things when I find other issues when I work on this project again.  I have some nuxt/content projects as well and when I work on them I will very proooooobably use this there too!

**Comment by patinthehat** [comment]
@Gompje I'm glad I could help and that it's all working for you! I'm always looking for people to report issues so I can take care of them, thank you.

I like the idea of ignoring certain components - maybe an option to filter out components you don't want based on the component name.  Stay tuned.

Thanks again for your quick turnaround tests and working with me to get the issue resolved. :+1:

**Comment by Gompje** [comment]
> I like the idea of ignoring certain components - maybe an option to filter out components you don't want based on the component name. Stay tuned.

Maybe it could be as simple as filter out 'unknown' when option is set and then ignores all these that trigger`filename: <project root>/unknown.js`, because I think this is something he didn't find in the project components; therefore it's vendor? Just saying because maybe thats an easy option and usefull option to have as well; especially for people like me who use Vuetify and really do not want to list/find out every component all my vendor packages have.. 😏

**Comment by patinthehat** [comment]
That sounds like a good place to start.  I'll add it to the next release - I have one in the works right now.
