### ISSUE TITLE
Requests being blocked due to https

### ISSUE THREAD

**Issue by justinhartman** [permafrost-dev/vue-ray#51]
**Describe the bug**

I am running an Inertia/Jetstream Laravel application with Vue 3 and had an issue trying to get this package to work with my app. I did however [get it to work with this fix](https://github.com/permafrost-dev/vue-ray/issues/6#issuecomment-1081909995) but now I am get a good 50/60 repeated XHR blocked requests with this configuration:

![20220329_160416](https://user-images.githubusercontent.com/717118/160629610-20701b82-5748-4448-82cf-987c4f46fd22.png)

This is happening because my localhost site runs off of SSL so my requests are being blocked due to insecure requests. If I run the app using `php artisan serve` I don't get these issues and the site is logging requests to Ray as expected.

My question to you is if there is a way to use `https` instead of `http` for the host configuration? Current there is only a `host` option but no matter what you use it will always try to send/get requests from http.

**Comment by justinhartman** [comment]
There's an undocumented `scheme` option which I managed to track down in the source. Adding this `scheme: 'https'` to my options solved my XHR issues. Here is my final options setup for my Inertia app if anyone is interested:

```javascript
.use(RayPlugin, {
    interceptErrors: true,
    host: 'localhost',
    scheme: 'https',
    port: 23517,
    showComponentEvents: ['created', 'updated'],
    nodeRaySettings: {
        interceptConsoleLog: true,
    },
})
```

**Comment by patinthehat** [comment]
@justinhartman Thanks for the heads up - I'll update the docs accordingly.
