### ISSUE TITLE
I am unable to run it in a Jetstream/Inertia based application

### ISSUE THREAD

**Issue by vedovelli** [permafrost-dev/vue-ray#6]
Thanks in advance for taking care of this! 😃

**Describe the bug**

After following the installation steps, the application crashes.

**Expected behavior**

After installation and attachment to the Vue application, everything should work.

**Screenshots**

Package.json
![CleanShot 2021-03-26 at 07 20 02](https://user-images.githubusercontent.com/151001/112590997-f9af6680-8e03-11eb-81cd-88dd59fe967e.png)

app.js
![CleanShot 2021-03-26 at 07 20 30](https://user-images.githubusercontent.com/151001/112591026-02a03800-8e04-11eb-966a-0c9a5f0e1969.png)

Error message on Chrome Devtools
![CleanShot 2021-03-26 at 07 20 18](https://user-images.githubusercontent.com/151001/112591053-0e8bfa00-8e04-11eb-8fe9-edd834f8a563.png)

**Environment (please complete the following information):**

 - OS: MacOSX
 - Vue Version Vue 3.0.5

**Comment by patinthehat** [comment]
@vedovelli I'm looking into this.  Stand by.

**Comment by vedovelli** [comment]
Thank you @patinthehat ! It works like a charm!

**Comment by justinhartman** [comment]
> ```js
> // import RayPlugin using require()
> const { RayPlugin } = require('vue-ray');
> ```

With a Laravel 9.5.1, Inertia Vue 3.2.31 Jetstream application this is the only way I could get this to work:

```javascript
require('./bootstrap');
require('./credits');

import { createApp, h } from 'vue';
import { createInertiaApp } from '@inertiajs/inertia-vue3';
import { InertiaProgress } from '@inertiajs/progress';

// This is the only way to get it to work...
const { RayPlugin } = require('vue-ray');

const appName = window.document.getElementsByTagName('title')[0]?.innerText || 'Laravel';

createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) => require(`./Pages/${name}.vue`),
    setup({ el, app, props, plugin }) {
        return createApp({ render: () => h(app, props) })
            .use(plugin)
            .use(RayPlugin, {
                interceptErrors: true,
                host: '127.0.0.1',
                port: 23517,
                showComponentEvents: ['created', 'mounted', 'unmounted', 'updated'],
                nodeRaySettings: {
                    interceptConsoleLog: true,
                },
            })
            .mixin({ methods: { route } })
            .mount(el);
    },
});
```
