### ISSUE TITLE
Don't show all the logs - Is there a way to only show certain log's

### ISSUE THREAD

**Issue by whitespacecode** [permafrost-dev/vue-ray#60]
### Discussed in https://github.com/permafrost-dev/vue-ray/discussions/57

<div type='discussions-op-text'>

<sup>Originally posted by **JoeriTheGreat** April 21, 2022</sup>
Is their a way you can filter out some log's ?
I'm working with vite and vue3 and each time a file is changed this i logged into ray.
![image](https://user-images.githubusercontent.com/37139936/164491024-4ee268ff-0a9a-4e86-b203-f558b7cc6df3.png)</div>

**Comment by patinthehat** [comment]
Thanks so much for the idea! Right now this isn't possible, but I'd happily accept a PR that adds this functionality. :+1:

**Comment by JoeriTheGreat** [comment]
> Thanks so much for the idea! Right now this isn't possible, but I'd happily accept a PR that adds this functionality. 👍

Thank you for looking into this, i'm trying to understand the functionality. 
Right now you can use this
```
sending_payload_callback: (ray, payloads) => {
   if (payloads[0].getType() === 'log') {

    }
},
```
I can't seem to log what 'payloads' or getType is.. It's not that this can be used in any way ?

**Comment by patinthehat** [comment]
Closed due to inactivity. Please open a new issue if you're still experiencing an issue. Thanks!
