### ISSUE TITLE
Does not seem to work with Vue 3 + Vite (rollup) in production

### ISSUE THREAD

**Issue by vesper8** [permafrost-dev/vue-ray#64]
I'm using your vue 3 version and it works great on my dev, but when I build for prod, with Vite, which uses rollup, I then get bombarded with many dozen of these:

```

ReferenceError: require is not defined
    at Proxy.beforeCreate (index.f32d143e.js:92:2693)
    at hs (index.f32d143e.js:1:13359)
    at Ir (index.f32d143e.js:1:13430)
    at Jv (index.f32d143e.js:1:26666)
    at TR (index.f32d143e.js:1:24979)
    at Yb (index.f32d143e.js:1:52131)
    at n$ (index.f32d143e.js:1:51714)
    at t$ (index.f32d143e.js:1:51353)
    at ye (index.f32d143e.js:1:37769)
    at ve (index.f32d143e.js:1:37648)
```

I've isolated the error to vue-ray, so now I only use it on dev.

If you have any idea on how to resolve this, I did enjoy using it on prod occasionally.

Many thanks!

**Comment by ryantbrown** [comment]
Vite does not work in development either, there are TS and connection errors.

**Comment by amfischer** [comment]
I'm using Vite and Vue3 and I can't get `vue-ray` or `node-ray` to work on a development environment. 

vue-ray console error
![error-vue-ray](https://github.com/permafrost-dev/vue-ray/assets/11054087/bebfd0f4-64a5-4324-bebd-ebdff42ddf26)

node-ray console error
![error-node-ray](https://github.com/permafrost-dev/vue-ray/assets/11054087/6704eeb3-b897-4898-b54b-bc172fa30815)

**Comment by patinthehat** [comment]
Closed due to inactivity. Please open a new issue if you're still experiencing an issue. Thanks!
